name: Deploy

on: workflow_dispatch

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: 'dev'
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fetch-depth: 0
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    environment: 'qa'
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fetch-depth: 0
