name: Release

on: 
  push:
    branches:
    - main

jobs:
  release:
    name: Create release version
    runs-on: ubuntu-latest
    steps:
    - name: Using Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: v16.3.0
    - name: Tagging
      run: |
        npm install
        npx auto shipit
