name: Release

on: workflow_dispatch

jobs:
  release:
    name: Create release version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        fetch-depth: 0
      
    - name: Use Nodejs 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: auto-deps
        restore-keys: auto-deps
        
    - name: Initialize Repo
      run: npm install --no-save auto @auto-it/git-tag @auto-it/jira
      
    - name: Set up git user
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.email "ahytha@relaynetwork.com"
        git config --global user.name "Auto Release Agent"
        
    - name: Create changelog
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npx auto changelog
      
    - name: Bump version
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        export BUMP=$(npx auto version)
        export TAG=$(npm version $BUMP -m "Released version %s on $(date)")
        export BRANCH=release/$(date '+%Y-%m-%d')-$TAG
        echo "Branch is $BRANCH"
        git push --atomic origin main $TAG
        git checkout -b $BRANCH
        git push --atomic origin $BRANCH
