name: Release

on: workflow_dispatch

jobs:
  release:
    name: Create release version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Prepare Repository
      run: git fetch --unshallow --tags
      
    - name: Unset header
      run: git config --local --unset http.https://github.com/.extraheader
      
    - name: Use Nodejs 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-deps-${{hashFiles('package-lock.json')}}
        restore-keys: npm-deps-${{hashFiles('package-lock.json')}}
        
    - name: Initialize Repo
      run: npm install --no-save auto @auto-it/git-tag @auto-it/jira

    - name: Create release branch
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        TAG=$(npm version $(npx auto version) -m "Released version %s on $(date)")
        BRANCH=release/$(date '+%Y-%m-%d')-$TAG
        git checkout -b $BRANCH
        git push --set-upstream origin/$BRANCH
        npx auto changelog
        git push --atomic origin $BRANCH $TAG
        git checkout main
        git merge $BRANCH
        git push origin main
