name: Release

on: workflow_dispatch

jobs:
  release:
    name: Create release version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    
    - name: Prepare Repository
      run: git fetch --unshallow --tags
      
    - name: Use Nodejs 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: auto-deps
        restore-keys: auto-deps
        
    - name: Initialize Repo
      run: npm install --no-save auto @auto-it/git-tag @auto-it/jira

    - name: Create release branch
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --global user.email "ahytha@relaynetwork.com"
        git config --global user.name "Auto Release Agent"
        npx auto changelog
        echo "finished creating changelog"
        BUMP=$(npx auto version)
        echo "Bumping version by" $BUMP
        TAG=$(npm version $BUMP -m "Released version %s on $(date)")
        echo "Set version and tag"
        BRANCH=release/$(date '+%Y-%m-%d')-$TAG
        echo "Branch is $BRANCH"
        git push --follow-tags -u origin $BRANCH
